language: node_js
node_js:
- '4'
branches:
  only:
  - dev
before_install:
- export TZ='Asia/Shanghai'
# 解密id_rsa_blog.enc 输出到.ssh/文件夹下，命名为id_rsa
- openssl aes-256-cbc -K $encrypted_b9019d7122e3_key -iv $encrypted_b9019d7122e3_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
# 设置id_rsa文件权限
- chmod 600 ~/.ssh/id_rsa
# 添加ssh密钥
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
# 添加ssh配置文件
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "zelsonia"
- git config --global user.email 2277909950@qq.com
install: 
- npm install
# ERROR Deployer not found: git 所以要加上
- npm install --save hexo-deployer-git
- npm install --save hexo-util
script:
- hexo clean
- hexo g
# 希望能不出现确认The authenticity of host
- service sshd restart 

after_success:
- hexo deploy
